// <auto-generated />
using ExampleEntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExampleEntityFramework.Migrations
{
    [DbContext(typeof(ExampleContext))]
    partial class ExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("EnTier.DataAccess.JsonFile.MarkedFilterResult<ExampleEntityFramework.StoragesModels.PostStg, long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpirationTimeStamp")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResultId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PostsFilterResults");
                });

            modelBuilder.Entity("EnTier.DataAccess.JsonFile.MarkedSearchIndex<ExampleEntityFramework.StoragesModels.PostStg, long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IndexCorpus")
                        .HasColumnType("TEXT");

                    b.Property<long>("ResultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PostsSearchIndex");
                });

            modelBuilder.Entity("ExampleEntityFramework.StoragesModels.PostStg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<long>("PostStgId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
