using System;
using System.Collections.Generic;
using System.Linq;
using Acidmanic.Utilities.Reflection.ObjectTree;

namespace EnTier.Utility
{
    public static class IdHelper
    {
        public static AccessNode GetIdLeaf<TEntity, TId>()
        {
            var idLeaf = GetAutoGeneratedLeaf<TEntity, TId>();

            if (idLeaf != null)
            {
                return idLeaf;
            }
            var idType = typeof(TId);

            idLeaf = GetUniqueLeaves<TEntity>()
                    .FirstOrDefault(l => l.Type == idType);

            if (idLeaf != null)
            {
                return idLeaf;
            }
            
            idLeaf = GetLeafByName<TEntity>("Id","ID","id","iD")
                .FirstOrDefault(l => l.Type == idType);

            return idLeaf;
        }

        
        public static IEnumerable<AccessNode> GetLeafByName<TEntity>(params string[] acceptableNames)
        {

            return GetLeaves<TEntity>(l => acceptableNames.Contains(l.Name));
        }
        
        public static AccessNode GetAutoGeneratedLeaf<TEntity, TId>()
        {
            var idType = typeof(TId);
            
            return GetLeaves<TEntity>(l => l.IsAutoValued && l.Type == idType)
                .FirstOrDefault();
        }
        
        
        public static IEnumerable<AccessNode> GetUniqueLeaves<TEntity>()
        {
            return GetLeaves<TEntity>(l => l.IsAutoValued );
        }

        private static IEnumerable<AccessNode> GetLeaves<TEntity>(Func<AccessNode, bool> selector)
        {
            var accessNode = ObjectStructure.CreateStructure<TEntity>(false);
            
            var leaves = accessNode
                .EnumerateLeavesBelow()
                .Where(selector);

            return leaves;
        }
       
        
    }
}