using Meadow.Reflection.Conventions;
using Meadow.Requests.FieldManipulation;

namespace EnTier.DataAccess.Meadow.GenericCrudRequests
{
    public class InsertStorageRequest<TStorage> : StorageRequest<TStorage, TStorage>
        where TStorage : class, new()
    {
        protected override void OnFieldManipulation(IFieldManipulator<TStorage> toStorage, IFieldManipulator<TStorage> fromStorage)
        {
            base.OnFieldManipulation(toStorage, fromStorage);

            if (AutogeneratedFields.Count>0)
            {
                AutogeneratedFields.ForEach(f => toStorage.Exclude(f.Key));
            }
        }

        protected override string PickProcedureName(NameConvention nameConvention)
        {
            return nameConvention.InsertProcedureName;
        }

        public InsertStorageRequest() : base(typeof(TStorage))
        {
        }
    }
}